### ISSUE TITLE
Website doesn't work OOB in Azure Webapps

### ISSUE THREAD

**Issue by molant** [mguinness/NoticeBoard#1]
There are a couple things that make this site not work OOB in Azure Webapps:
- The root of the project is not on `/` but `NoticeBoard` (I've changed that in the deployment)
- It requires of some commands to be executed in order to work (from what I read in the readme.md). 

/cc @aarongustafson

**Comment by mguinness** [comment]
Thanks for your feedback.  Were you using the publish dialog in VS 2015 to target Microsoft Azure App Service?  That should take care of the correct path.  Any relation to this [GitHub issue](https://github.com/aspnet/Home/issues/1636)?

Regarding the SQLite database, are the [EF Migrations options](https://github.com/aspnet/Tooling/blob/master/specs/web-publish-ef-migrations.md) not shown in the publish dialog?  If not, you could use the sample database from the release version for your deployment.

**Comment by molant** [comment]
The website is synced directly with the GitHub project, there is no manual deployment. If you have one script that replaces the default kudu script then please add it to the repo sooner rather than later.

**Comment by mguinness** [comment]
@molant - I've modified the code to apply the migrations automatically rather than manually running them.  Next time you pull it should create the database schema for you.

**Comment by molant** [comment]
@mguinness I'm now getting a custom 500 error: http://notice-board-10kapart2016.azurewebsites.net/

Any ideas?

**Comment by mguinness** [comment]
I would need further information to troubleshoot, even static files aren't being served.  Setting environment variable ASPNETCORE_ENVIRONMENT=Development should emit a more detailed error message.

**Comment by molant** [comment]
Done. Error with `project.json` but I can't find that file anywhere. We do have to wwwroot folders like the issue you linked.

**Comment by mguinness** [comment]
File [project.json](https://github.com/mguinness/NoticeBoard/blob/master/src/NoticeBoard/project.json) is in repo so hope that helps.  Let me know if you're still having issues.

**Comment by molant** [comment]
@mguinness I've done a clean deploy and there is another issue now:

> Could not load file or assembly 'Microsoft.EntityFrameworkCore.SqlServer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

**Comment by mguinness** [comment]
I pushed up new files that changed model annotation from SqlServer:ValueGenerationStrategy to Autoincrement.  Not sure why this problem  just surfaced, but see if this fixes the issue.

**Comment by molant** [comment]
@mguinness pushed the new version and seems to be working: https://notice-board-10kapart2016.azurewebsites.net/
Let me know if you see any issue.

Thanks!

**Comment by mguinness** [comment]
@molant I was able to login and change content and all appears to be working as expected, thanks for your patience whilst working through the issues.
